### PR TITLE
Move to building from Pypi package for automatic updates

### PR DESCRIPTION
**Pull request by wtclarke**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

This proposes a change to building the `Sigpy` conda(-forge) package from the `Pypi` package. The major advantage fo this is that whenever a new version is pushed to Pypi, conda-forge will automatically build a package for the new version and open a PR to publish it. (The latter step can be automatically run if wanted). Seeing as `Sigpy` already has CI for uploading new `Pypi` versions, this would also automate the publishing of conda versions.

See the [doc](https://conda-forge.org/docs/maintainer/updating_pkgs.html#how-does-regro-cf-autotick-bot-create-automatic-version-updates) for more info on how this works.

### CODE REVIEW

**Comment by wtclarke** [comment]
@conda-forge-admin, please rerender

**Comment by wtclarke** [comment]
Note I've skipped one test (https://github.com/mikgroup/sigpy/blob/main/tests/test_version.py) because it hasn't got the right version string in.

Why do you test when building a package and not when you push / PR in to the repo? It's too late by the time you are publishing the package.

**Review by gschramm — COMMENTED** [review]
Looks good to me.

**Comment by gschramm** [comment]
> Note I've skipped one test (https://github.com/mikgroup/sigpy/blob/main/tests/test_version.py) because it hasn't got the right version string in.
> 
> Why do you test when building a package and not when you push / PR in to the repo? It's too late by the time you are publishing the package.

@frankong Can you clarify why there is the static "test_version"?

**Review by frankong — APPROVED** [review]
Looks good to me! the static version test was probably legacy code

**Comment by wtclarke** [comment]
@gabuzi Good catch. I've updated to match the `requirements.txt`.

**Comment by gschramm** [comment]
sigpy 0.1.25 still used the deprecated `np.float` (instead of `np.float32` or `np.float64`) which is why I had to require numpy<=1.19. Since this issue is now fixed, requiring numpy<=1.20 is correct.

Are we ready to merge?

**Comment by wtclarke** [comment]
I believe so.

**Review by gschramm — APPROVED** [review]

**Pull request merged**
